apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: gp2 #changed from manual to gp2 which is a default storage class offered by aws
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi #changed as per the requirement of the project